### ISSUE TITLE
Issues with dual drives.

### ISSUE THREAD

**Issue by sverrewl** [vbousquet/vpx_lightmapper#6]
Use of relative path seems to have some issues. Not sure how important VPXMeshes.blend is in the process; but, it will also complain and skip generating a new VLM vpx as the path gets "corrupted".

**Comment by vbousquet** [comment]
Not sure if this were a bug here but setting Blender filepath using Blender relative filepath format can be cumbersome. 0.0.3 adds UI to easily set it up, including in a multi drive situation
