### ISSUE TITLE
use_obj_pos should use the sync obj property

### ISSUE THREAD

**Issue by mpcarr** [vbousquet/vpx_lightmapper#8]
When setting a sync object and checking use obj position in vlm settings, the sync obj's property isn't used on export.

https://github.com/vbousquet/vpx_lightmapper/blob/61d42fdb8dff7145298cb867f7792bd190c95276/addons/vpx_lightmapper/vlm_export.py#L363

**Comment by vbousquet** [comment]
Fixed by https://github.com/vbousquet/vpx_lightmapper/commit/b302fe1afe5f053e41066379266893cc428ad032
